name: Package & Release

on:
  release:
    types: [ published ]

permissions:
  contents: write

jobs:
  package:
    name: Package extension source
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Install vsce
        run: npm install -g @vscode/vsce

      - name: Package extension 
        run: vsce package --out rust-mod-creator-${{ github.event.release.tag_name }}.vsix

      - name: Publish extension
        env:
          VSCE_PAT: ${{ secrets.VSCE_TOKEN }}
        run: vsce publish --packagePath rust-mod-creator-${{ github.event.release.tag_name }}.vsix

      - name: Publish GitHub release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ github.event.release.tag_name }} rust-mod-creator-${{ github.event.release.tag_name }}.vsix --clobber
